# Generated by Django 2.2.5 on 2024-01-31 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20240125_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PETS', 'Pets'), ('APPAREL', 'Apparel'), ('TOYS', 'Toys')], default=1, max_length=60),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
